### PR TITLE
make compatible with 3.11

### PR DESCRIPTION
**Pull request by rickwierenga**
address https://github.com/rbarrois/aionotify/issues/18. (drops support for 3.4, I think)

### CODE REVIEW

**Comment by oolivero45** [comment]
@rbarrois - is there any progress towards getting this merged?
The lack of Python 3.11 support from this module causes Home Assistant's [keyboard_remote integration](https://www.home-assistant.io/integrations/keyboard_remote/) to break in the next release of Home Assistant, as said release runs on Python 3.11.

**Comment by spumer** [comment]
@rbarrois can you transfer project to new maintainer?

**Comment by wrosko** [comment]
@oolivero45 @spumer  I just sent @rbarrois messages on Linkedin and Twitter regarding this. Maybe if enough of us reach out they might be able to help, otherwise a fork might be in store?

**Comment by rbarrois** [comment]
Fixed! Thanks a lot.

As a side note, I'm more easily reached by email than over social media :)

**Comment by wrosko** [comment]
@rbarrois Awesome, thanks :)

**Pull request closed without merging**
